### ISSUE TITLE
Multi-cursor support.

### ISSUE THREAD

**Issue by anonymous1184** [frogstair/number-system-converter#1]
Hello!

First thing first: even though is really low on installs, is one of the most used extensions for me, thanks a lot for thinking about it and share it.

That said, I often find myself converting more than a single number and multi-cursor selection is basically always at play. My current workaround is to cut the chunk of numbers, paste them in Notepad2 and do the conversion there.

Are there any plans to support more than a single number?

**Comment by crabtutorial** [comment]
Added the feature, thanks for the feedback!!

**Comment by anonymous1184** [comment]
Amazing, thanks a lot for your time and the quick turn around. No more Notepad for me! <3
